---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: shutdown
      command: /sbin/shutdown -h now

    - name: wait for it to go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped

