---
#- name: Download Kafka tar file
#  become: yes
#  ansible.builtin.get_url:
#    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
#    dest: /tmp
#    mode: 0755
#  register: kafka_tar_file
- name: Set the kafka tar file variable
  set_fact:
    kafka_tar_file: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

- name: Check if Kafka tar file already exists
  ansible.builtin.stat:
    path: "{{ kafka_tar_file }}"
  register: kafka_tar_file_stat

- name: Download Kafka tar file
  become: yes
  ansible.builtin.get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp"
    mode: 0755
#  register: kafka_tar_file
  when: not kafka_tar_file_stat.stat.exists
