---
- name: Create kafka group
  become: yes
  group:
    name: '{{ kafka_group }}'
    state: present
    system: yes
  
- name: Create kafka user
  become: yes
  user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    createhome: no
    system: yes

- name: Create kafka directory
  become: yes
  file:
    path: "{{ kafka_installation_path }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
    mode: 0755
    recurse: true

- name: download | Download 
  become: yes
  import_tasks: download.yml
  when:
    - not skip_downloads|default(false)

- name: Extract Kafka tar file
  become: yes
  unarchive:
    remote_src: true
#    src: "{{ kafka_tar_file.dest }}"
    src: "{{ kafka_tar_file }}"
    dest: "{{ kafka_installation_path }}"
    extra_opts: [--strip-components=1]
#    creates: "{{ kafka_installation_path }}/bin/kafka-server-start.sh"
  register: _extract

- name: configuration | set log directory and cluster metadata
  import_tasks: configuration.yml
